export const FIRST_100_COINS = [
    "Bitcoin",
    "Ethereum",
    "Dogecoin",
    "Litecoin",
    "Namecoin",
    "Terracoin",
    "Peercoin",
    "Novacoin",
    "Feathercoin",
    "Freicoin",
    "Ixcoin",
    "WorldCoin",
    "Digitalcoin",
    "Goldcoin",
    "Phoenixcoin",
    "Megacoin",
    "Infinitecoin",
    "Primecoin",
    "Anoncoin",
    "CasinoCoin",
    "Emerald Crypto",
    "XRP",
    "Quark",
    "Zetacoin",
    "TagCoin",
    "Public Index Network",
    "Nxt",
    "Unobtanium",
    "Datacoin",
    "Deutsche eMark",
    "Dogecoin",
    "Diamond",
    "HoboNickels",
    "Orbitcoin",
    "Omni",
    "FedoraCoin",
    "Dimecoin",
    "42-coin",
    "Vertcoin",
    "DigiByte",
    "SmartCoin (SMC)",
    "ReddCoin",
    "PotCoin",
    "Blakecoin",
    "Maxcoin",
    "Dash",
    "Counterparty",
    "MintCoin",
    "DopeCoin",
    "Auroracoin",
    "Peseta Digital",
    "Marscoin",
    "Magic Internet Money",
    "Uniform Fiscal Object",
    "BlackCoin",
    "Photon",
    "Myriad",
    "DNotes",
    "Einsteinium",
    "ECC",
    "MonaCoin",
    "Rubycoin",
    "Bela",
    "FairCoin",
    "e-Gulden",
    "Gulden",
    "Groestlcoin",
    "PetroDollar",
    "PLNcoin",
    "WhiteCoin",
    "Bitstar",
    "Quebecoin",
    "BlueCoin",
    "MaidSafeCoin",
    "Bitcoin Plus",
    "NewYorkCoin",
    "Pinkcoin",
    "Dreamcoin",
    "Energycoin",
    "VeriCoin",
    "Monero",
    "Litecoin Plus",
    "Curecoin",
    "SuperCoin",
    "Motocoin",
    "CloakCoin",
    "BitSend",
    "Coin2.1",
    "Bytecoin",
    "Navcoin",
    "Startcoin",
    "DigitalNote",
    "Boolberry",
    "HempCoin",
    "Stealth",
    "Clams",
    "BitShares",
    "Viacoin",
    "I/O Coin",
    "Cryptonite",
    "Carboncoin",
    "CannabisCoin"
];
